// Auto-generate src/data/generated-logos.ts from png files in src/logos/
// Run via: node scripts/gen-logos.mjs
import { promises as fs } from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');
const logosDir = path.join(projectRoot, 'src', 'logos');
const outFile = path.join(projectRoot, 'src', 'data', 'generated-logos.ts');

function toIdentifier(slug) {
  // Convert slug/file stem to a safe TS identifier
  let id = slug.replace(/[^a-zA-Z0-9_]/g, '_');
  if (/^[0-9]/.test(id)) id = '_' + id;
  return id;
}

async function main() {
  const entries = await fs.readdir(logosDir, { withFileTypes: true });
  const pngs = entries
    .filter((e) => e.isFile() && e.name.toLowerCase().endsWith('.png'))
    .map((e) => e.name)
    .sort((a, b) => a.localeCompare(b));

  const imports = [];
  const mappings = [];

  for (const file of pngs) {
    const slug = file.replace(/\.png$/i, '');
    const ident = toIdentifier(slug);
    // Skip default-image, it will be used as a fallback in banks.ts
    if (slug === 'default-image') continue;
    imports.push(`import ${ident} from "../logos/${file}";`);
    mappings.push(`  "${slug}": ${ident},`);
  }

  const content = `// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/gen-logos.mjs
${imports.join('\n')}

export const LOGOS: Record<string, string> = {
${mappings.join('\n')}
};
`;

  await fs.mkdir(path.dirname(outFile), { recursive: true });
  await fs.writeFile(outFile, content, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`Generated ${path.relative(projectRoot, outFile)} with ${mappings.length} entries.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
