// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/gen-logos.mjs
import access_bank_diamond from "../logos/access-bank-diamond.png";
import access_bank from "../logos/access-bank.png";
import alat_by_wema from "../logos/alat-by-wema.png";
import asosavings from "../logos/asosavings.png";
import cemcs_microfinance_bank from "../logos/cemcs-microfinance-bank.png";
import citibank_nigeria from "../logos/citibank-nigeria.png";
import ecobank_nigeria from "../logos/ecobank-nigeria.png";
import ekondo_microfinance_bank from "../logos/ekondo-microfinance-bank.png";
import fidelity_bank from "../logos/fidelity-bank.png";
import first_bank_of_nigeria from "../logos/first-bank-of-nigeria.png";
import first_city_monument_bank from "../logos/first-city-monument-bank.png";
import globus_bank from "../logos/globus-bank.png";
import guaranty_trust_bank from "../logos/guaranty-trust-bank.png";
import heritage_bank from "../logos/heritage-bank.png";
import keystone_bank from "../logos/keystone-bank.png";
import kuda_bank from "../logos/kuda-bank.png";
import lotus_bank from "../logos/lotus-bank.png";
import moniepoint_mfb_ng from "../logos/moniepoint-mfb-ng.png";
import paga from "../logos/paga.png";
import palmpay from "../logos/palmpay.png";
import paycom from "../logos/paycom.png";
import polaris_bank from "../logos/polaris-bank.png";
import sparkle_microfinance_bank from "../logos/sparkle-microfinance-bank.png";
import stanbic_ibtc_bank from "../logos/stanbic-ibtc-bank.png";
import standard_chartered_bank from "../logos/standard-chartered-bank.png";
import sterling_bank from "../logos/sterling-bank.png";
import taj_bank from "../logos/taj-bank.png";
import union_bank_of_nigeria from "../logos/union-bank-of-nigeria.png";
import united_bank_for_africa from "../logos/united-bank-for-africa.png";
import wema_bank from "../logos/wema-bank.png";
import zenith_bank from "../logos/zenith-bank.png";

export const LOGOS: Record<string, string> = {
  "access-bank-diamond": access_bank_diamond,
  "access-bank": access_bank,
  "alat-by-wema": alat_by_wema,
  "asosavings": asosavings,
  "cemcs-microfinance-bank": cemcs_microfinance_bank,
  "citibank-nigeria": citibank_nigeria,
  "ecobank-nigeria": ecobank_nigeria,
  "ekondo-microfinance-bank": ekondo_microfinance_bank,
  "fidelity-bank": fidelity_bank,
  "first-bank-of-nigeria": first_bank_of_nigeria,
  "first-city-monument-bank": first_city_monument_bank,
  "globus-bank": globus_bank,
  "guaranty-trust-bank": guaranty_trust_bank,
  "heritage-bank": heritage_bank,
  "keystone-bank": keystone_bank,
  "kuda-bank": kuda_bank,
  "lotus-bank": lotus_bank,
  "moniepoint-mfb-ng": moniepoint_mfb_ng,
  "paga": paga,
  "palmpay": palmpay,
  "paycom": paycom,
  "polaris-bank": polaris_bank,
  "sparkle-microfinance-bank": sparkle_microfinance_bank,
  "stanbic-ibtc-bank": stanbic_ibtc_bank,
  "standard-chartered-bank": standard_chartered_bank,
  "sterling-bank": sterling_bank,
  "taj-bank": taj_bank,
  "union-bank-of-nigeria": union_bank_of_nigeria,
  "united-bank-for-africa": united_bank_for_africa,
  "wema-bank": wema_bank,
  "zenith-bank": zenith_bank,
};
